spring:
    cloud:
        config: 
            enabled: false
keycloak:
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:8080/auth
  realm: autopecas
  ssl-required: external
  resource: client-service
  credentials:
    secret: nDyjPZogvtEgl6Ay4NLEews2Wd2AcZq9
  use-resource-role-mappings: true
  bearer-only: true
server:
  port: 8081
